# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Halkilahti
email: jone at halkilahti dot fi
description: |
  Thanks for stopping by.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://halkilahti.fi" # the base hostname & protocol for your site
#twitter_username: jhalkilahti
github_username:  Nucleotide

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal
